language: cpp
compiler: gcc
        
branches:
    only:
        - dev
        
include:    
# works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - sudo apt-get install lbglfw3-dev libglfw3
    - sudo apt-get install libboost-all-dev
script:
    - cd VapeEngine
    - mkdir build
    - cd build
    - ccmake ..
    - make
