dist: trusty
language: cpp
compiler: gcc
        
branches:
    only:
        - dev
        
include:    
# works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7 
            - g++-7
            - cmake-data
            - cmake
      env:
        - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=gcc-7"

install:
    - sudo apt-get install libboost-all-dev
    - sudo apt-get install libglm libglm-dev
    - sudo add-apt-repository -y ppa:pyglfw/pyglfw && sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends libglfw3-dev libglew-dev libxrandr-dev libxi-dev libxxf86vm-dev
script:
    #- export CC=gcc-7
    #- export CXX=g++-7
    - cd VapeEngine
    - (mkdir build && cd build && cmake .. ${CMAKE_OPTIONS})
    - make
