#ifndef VAPEENGINE_PRIMITIVESHAPES_H
#define VAPEENGINE_PRIMITIVESHAPES_H

namespace VapeRenderer {
    enum PrimitiveShapes {CUBE, PLANE, PYRAMID, CYLINDER, SPHERE};
}

#endif //VAPEENGINE_PRIMITIVESHAPES_H
